<?php
// test_smtp.php
// Usage: php test_smtp.php recipient@example.com
// This script reads SMTP settings from config.php and attempts a simple SMTP send

require_once __DIR__ . '/config.php';

$to = $argv[1] ?? null;
if (!$to) {
    echo "Usage: php test_smtp.php recipient@example.com\n";
    exit(1);
}

$host = SMTP_HOST;
$port = (int)SMTP_PORT;
$user = SMTP_USER;
$pass = SMTP_PASS;
$secure = SMTP_SECURE; // 'tls' or 'ssl' or empty

function recv($fp) {
    $data = '';
    while (($line = fgets($fp)) !== false) {
        $data .= $line;
        // responses that begin with 220/250/354/etc end with a space after the code
        if (preg_match('/^\d{3} /m', $line)) break;
    }
    return $data;
}

echo "Testing SMTP connection to {$host}:{$port} (secure={$secure})\n";

$timeout = 15;
$remote = ($secure === 'ssl') ? 'ssl://' . $host : $host;
$fp = @stream_socket_client($remote . ':' . $port, $errno, $errstr, $timeout);
if (!$fp) {
    echo "Connection failed: $errno - $errstr\n";
    exit(1);
}

stream_set_timeout($fp, $timeout);
echo "Connected, waiting for banner...\n";
echo recv($fp);

fwrite($fp, "EHLO localhost\r\n");
echo "EHLO ->\n" . recv($fp);

if ($secure === 'tls') {
    fwrite($fp, "STARTTLS\r\n");
    echo "STARTTLS ->\n" . recv($fp);
    if (!stream_socket_enable_crypto($fp, true, STREAM_CRYPTO_METHOD_TLS_CLIENT)) {
        echo "Failed to enable TLS\n";
        fclose($fp);
        exit(1);
    }
    // send EHLO again over TLS
    fwrite($fp, "EHLO localhost\r\n");
    echo "EHLO (after TLS) ->\n" . recv($fp);
}

// AUTH LOGIN
fwrite($fp, "AUTH LOGIN\r\n");
echo "AUTH LOGIN ->\n" . recv($fp);
fwrite($fp, base64_encode($user) . "\r\n");
echo "USER ->\n" . recv($fp);
fwrite($fp, base64_encode($pass) . "\r\n");
echo "PASS ->\n" . recv($fp);

// MAIL FROM / RCPT TO / DATA
fwrite($fp, "MAIL FROM:<" . MAIL_FROM_EMAIL . ">\r\n");
echo "MAIL FROM ->\n" . recv($fp);
fwrite($fp, "RCPT TO:<$to>\r\n");
echo "RCPT TO ->\n" . recv($fp);
fwrite($fp, "DATA\r\n");
echo "DATA ->\n" . recv($fp);
$body = "Subject: SMTP test from Katikamu\r\nFrom: " . MAIL_FROM_NAME . " <" . MAIL_FROM_EMAIL . ">\r\nTo: $to\r\n\r\nThis is a test message generated by test_smtp.php\r\n.";
fwrite($fp, $body . "\r\n");
echo "Sent DATA ->\n" . recv($fp);

fwrite($fp, "QUIT\r\n");
echo "QUIT ->\n" . recv($fp);
fclose($fp);

echo "Done. If the SMTP server accepted the message, it should be delivered to $to (or be in the server queue).\n";

?>
